spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appdb
    username: appuser
    password: appuser
    driver-class-name: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
